<?php
if($pageName=="catagories"||$pageName=="manage-categories"){
    $table="catageries";
}
if($pageName=="product"||$pageName=="manage-product"){
    $table="product";
}
if($pageName=="slider"||$pageName=="manage-slider"){
    $table="slider";
}
if($pageName=="reviews"||$pageName=="manage-reviews"){
    $table="reviews";
}
if($pageName=="user"||$pageName=="manage-user"){
    $table="user";
}
if($pageName=="profile"||$pageName=="manage-profile"){
    $table="profile";
}
?>